Fail karma runner when testsuite is defined but contain no tests or assertions
SAP/karma-ui5 pull request #228
Opened 2020-08-25 15:24 UTC by shahzeb79

https://github.com/SAP/karma-ui5/issues/226

Hi colleagues,
In S4 if some team has qunit and opa tests defined and loaded but OPA tests contains no tests or assertion, than runner should fail with error of "Suite with no tests should be removed". This happened when someone comment out testfiles in Alljourneys and runner still loads Alljourney but than reports no tests. In this case we see low coverages and team complains about it. So we want to configure runner so that we centrally can define some parameter in karma conf file to enable or disable failure in case of no tests.

Thanks

2020-08-25 15:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/karma-ui5?pullRequest=228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/karma-ui5?pullRequest=228) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/karma-ui5?pullRequest=228) it.</sub>

2020-08-26 10:21 UTC, shahzeb79 commented
@matz3 can you review this change?

2020-08-27 14:15 UTC, matz3 requested changes

2020-08-27 14:15 UTC, matz3 commented on lib/client/browser.js
>  							totalNumberOfTest += args.totalTests;
`totalNumberOfTest` should also be increased by 1 before calling `karma.info`
(Similar to the QUnit error reporting above (currently line 194)).

2020-08-27 14:15 UTC, matz3 commented on lib/framework.js
> +		if (!this.config.ui5.failOnNoTests) {
Please add a check so that the new option can only be used with `mode === "html"`.
With script mode it has no effect which might confuse a user.

2020-08-27 14:15 UTC, matz3 commented on test/unit/framework.test.js
> +			failOnNoTests: false,
To have a similar name like the karma config, let's use `failOnEmptyTestPage`

2020-08-31 10:35 UTC, matz3 commented
@shahzeb79 thanks for the changes.
I took some time to do final round-offs and add tests/docs.

Main change is that now an error is also logged even when to option is not enabled.
This should give users a hint that something is not right and that the option should be enabled.

With v3.0 we should enable this option by default.

2020-08-31 16:17 UTC, shahzeb79 commented
@matz3 thanks alot for your changes. Will it be available in v2.2.2 or some else?

2020-09-01 07:37 UTC, matz3 commented
v2.3.0, as it's a new feature. We'll do a release once this PR is reviewed and merged.

2020-09-01 08:17 UTC, RandomByte approved these changes

2020-09-02 08:08 UTC, merged